import { NgModule } from '@angular/core';
import { FaIconLibrary, FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faAddressBook as fasAddressBook,
  faAddressCard as fasAddressCard,
  faAngleDown as fasAngleDown,
  faAngleLeft as fasAngleLeft,
  faAngleRight as fasAngleRight,
  faAngleUp as fasAngleUp,
  faArchive as fasArchive,
  faArrowCircleUp as fasArrowCircleUp,
  faArrowDown as fasArrowDown,
  faArrowRight as fasArrowRight,
  faArrowRotateLeft as fasArrowRotateLeft,
  faArrowsAlt as fasArrowsAlt,
  faArrowsRotate as fasArrowsRotate,
  faArrowsSpin as fasArrowsSpin,
  faArrowsTurnToDots as fasArrowsTurnToDots,
  faArrowUp as fasArrowUp,
  faBan as fasBan,
  faBarsProgress as fasBarsProgress,
  faBed as fasBed,
  faBookBookmark as fasBookBookmark,
  faBookmark as fasBookmark,
  faBookOpen as fasBookOpen,
  faBorderAll as fasBorderAll,
  faBoxOpen as fasBoxOpen,
  faBriefcase as fasBriefcase,
  faBuilding as fasBuilding,
  faBuildingCircleArrowRight as fasBuildingCircleArrowRight,
  faBuildingCircleCheck as fasBuildingCircleCheck,
  faBus as fasBus,
  faCalculator as fasCalculator,
  faCalendar as fasCalendar,
  faCalendarAlt as fasCalendarAlt,
  faCalendarPlus as fasCalendarPlus,
  faCalendarWeek as fasCalendarWeek,
  faCamera as fasCamera,
  faCameraRotate as fasCameraRotate,
  faChalkboardTeacher as fasChalkboardTeacher,
  faChalkboardUser as fasChalkboardUser,
  faChartColumn as fasChartColumn,
  faCheck as fasCheck,
  faCheckCircle as fasCheckCircle,
  faCheckSquare as fasCheckSquare,
  faChevronCircleRight as fasChevronCircleRight,
  faChevronDown as fasChevronDown,
  faChevronLeft as fasChevronLeft,
  faChevronRight as fasChevronRight,
  faChevronUp as fasChevronUp,
  faCircle as fasCircle,
  faCircleNodes as fasCircleNodes,
  faCity as fasCity,
  faClinicMedical as fasClinicMedical,
  faClipboard as fasClipboard,
  faClipboardCheck as fasClipboardCheck,
  faClipboardList as fasClipboardList,
  faClipboardUser as fasClipboardUser,
  faClock as fasClock,
  faClone as fasClone,
  faCloudSun as fasCloudSun,
  faCog as fasCog,
  faCoins as fasCoins,
  faCommentDots as fasCommentDots,
  faComments as fasComments,
  faCompressAlt as fasCompressAlt,
  faCubes as fasCubes,
  faDatabase as fasDatabase,
  faDesktop as fasDesktop,
  faDoorClosed as fasDoorClosed,
  faDownload as fasDownload,
  faDumbbell as fasDumbbell,
  faDungeon as fasDungeon,
  faEarListen as fasEarListen,
  faEdit as fasEdit,
  faEllipsisH as fasEllipsisH,
  faEllipsisV as fasEllipsisV,
  faEnvelope as fasEnvelope,
  faExchange as fasExchange,
  faExchangeAlt as fasExchangeAlt,
  faExclamationTriangle as fasExclamationTriangle,
  faExpandAlt as fasExpandAlt,
  faEye as fasEye,
  faEyeSlash as fasEyeSlash,
  faFile as fasFile,
  faFileAlt as fasFileAlt,
  faFileArrowDown as fasFileArrowDown,
  faFileDownload as fasFileDownload,
  faFileInvoice as fasFileInvoice,
  faFileInvoiceDollar as fasFileInvoiceDollar,
  faFileLines as fasFileLines,
  faFileSignature as fasFileSignature,
  faFilter as fasFilter,
  faFlag as fasFlag,
  faFloppyDisk as fasFloppyDisk,
  faFolderOpen as fasFolderOpen,
  faGavel as fasGavel,
  faGear as fasGear,
  faGlobe as fasGlobe,
  faGraduationCap as fasGraduationCap,
  faGripLines as fasGripLines,
  faGripLinesVertical as fasGripLinesVertical,
  faHammer as fasHammer,
  faHandPaper as fasHandPaper,
  faHandshake as fasHandshake,
  faHistory as fasHistory,
  faHome as fasHome,
  faHospital as fasHospital,
  faHotel as fasHotel,
  faHouse as fasHouse,
  faHouseUser as fasHouseUser,
  faIdCardAlt as fasIdCardAlt,
  faInbox as fasInbox,
  faInfoCircle as fasInfoCircle,
  faLaptopHouse as fasLaptopHouse,
  faLayerGroup as fasLayerGroup,
  faLevelDownAlt as fasLevelDownAlt,
  faLink as fasLink,
  faList as fasList,
  faListAlt as fasListAlt,
  faListCheck as fasListCheck,
  faListOl as fasListOl,
  faListUl as fasListUl,
  faLock as fasLock,
  faMagnifyingGlass as fasMagnifyingGlass,
  faMap as fasMap,
  faMapMarkedAlt as fasMapMarkedAlt,
  faMapMarkerAlt as fasMapMarkerAlt,
  faMoneyBillAlt as fasMoneyBillAlt,
  faMoneyCheck as fasMoneyCheck,
  faMoneyCheckAlt as fasMoneyCheckAlt,
  faMusic as fasMusic,
  faNetworkWired as fasNetworkWired,
  faNewspaper as fasNewspaper,
  faPaperclip as fasPaperclip,
  faPassport as fasPassport,
  faPauseCircle as fasPauseCircle,
  faPencil as fasPencil,
  faPencilAlt as fasPencilAlt,
  faPeopleArrows as fasPeopleArrows,
  faPeopleArrowsLeftRight as fasPeopleArrowsLeftRight,
  faPersonWalkingDashedLineArrowRight as fasPersonWalkingDashedLineArrowRight,
  faPhone as fasPhone,
  faPiggyBank as fasPiggyBank,
  faPlus as fasPlus,
  faPlusCircle as fasPlusCircle,
  faPray as fasPray,
  faPrint as fasPrint,
  faProcedures as fasProcedures,
  faQuestion as fasQuestion,
  faReceipt as fasReceipt,
  faRedo as fasRedo,
  faRedoAlt as fasRedoAlt,
  faRestroom as fasRestroom,
  faRetweet as fasRetweet,
  faRing as fasRing,
  faSchool as fasSchool,
  faScroll as fasScroll,
  faSearch as fasSearch,
  faSearchDollar as fasSearchDollar,
  faShareAlt as fasShareAlt,
  faShieldAlt as fasShieldAlt,
  faShieldHalved as fasShieldHalved,
  faShoppingBasket as fasShoppingBasket,
  faSignOutAlt as fasSignOutAlt,
  faSitemap as fasSitemap,
  faSmile as fasSmile,
  faSpinner as fasSpinner,
  faSquare as fasSquare,
  faSquareXmark as fasSquareXmark,
  faStar as fasStar,
  faStickyNote as fasStickyNote,
  faStore as fasStore,
  faStreetView as fasStreetView,
  faSync as fasSync,
  faTable as fasTable,
  faTableCellsLarge as fasTableCellsLarge,
  faTableColumns as fasTableColumns,
  faTableList as fasTableList,
  faTag as fasTag,
  faTasks as fasTasks,
  faTh as fasTh,
  faThLarge as fasThLarge,
  faThList as fasThList,
  faThumbtack as fasThumbtack,
  faTimes as fasTimes,
  faTimesCircle as fasTimesCircle,
  faTimesSquare as fasTimesSquare,
  faToilet as fasToilet,
  faTrash as fasTrash,
  faTrashAlt as fasTrashAlt,
  faTriangleExclamation as fasTriangleExclamation,
  faTshirt as fasTshirt,
  faTty as fasTty,
  faUniversity as fasUniversity,
  faUser as fasUser,
  faUserAlt as fasUserAlt,
  faUserClock as fasUserClock,
  faUserCog as fasUserCog,
  faUserFriends,
  faUserGear as fasUserGear,
  faUserInjured as fasUserInjured,
  faUserLock as fasUserLock,
  faUserMinus as fasUserMinus,
  faUserPlus as fasUserPlus,
  faUsers as fasUsers,
  faUsersBetweenLines as fasUsersBetweenLines,
  faUserSecret as fasUserSecret,
  faUsersGear as fasUsersGear,
  faUserShield as fasUserShield,
  faUserSlash as fasUserSlash,
  faUserTag as fasUserTag,
  faUserTie as fasUserTie,
  faWarehouse as fasWarehouse,
  faWheelchair as fasWheelchair,
  faXmark as fasXmark,
} from '@fortawesome/free-solid-svg-icons';

/**
 * Please don't add more icons here (our main bundle is big enough!),
 * instead load the icons in the module that requires them.
 * See: libs\feature\scheduling\src\lib\scheduling.module.ts for an example
 *
 * Caveat: Loading icons the "correct" way can sometimes cause issues. Please try lazy loading new icons first and run
 * 'npx ng test ucase --runInBand (as well as the tests for your library)
 * If these tests pass, lazy loading is the right solution, but if they fail put your icons in here
 */
@NgModule({
  imports: [FontAwesomeModule],
})
export class IconLoaderModule {
  constructor(library: FaIconLibrary) {
    library.addIcons(
      fasAddressBook,
      fasAddressCard,
      fasAngleDown,
      fasAngleLeft,
      fasAngleRight,
      fasAngleUp,
      fasArchive,
      fasArrowCircleUp,
      fasArrowDown,
      fasArrowRight,
      fasArrowsAlt,
      fasArrowsSpin,
      fasArrowsTurnToDots,
      fasArrowUp,
      fasArrowRotateLeft,
      fasArrowsRotate,
      fasBan,
      fasBarsProgress,
      fasBed,
      fasBookBookmark,
      fasBookOpen,
      fasBookmark,
      fasBorderAll,
      fasBoxOpen,
      fasBriefcase,
      fasBuilding,
      fasBuildingCircleArrowRight,
      fasBus,
      fasCalculator,
      fasCalendar,
      fasCalendarAlt,
      fasCalendarPlus,
      fasCalendarWeek,
      fasCamera,
      fasCameraRotate,
      fasChartColumn,
      fasChalkboardTeacher,
      fasChalkboardUser,
      fasCheck,
      fasCheckCircle,
      fasCheckSquare,
      fasChevronCircleRight,
      fasChevronDown,
      fasChevronLeft,
      fasChevronRight,
      fasChevronUp,
      fasCircle,
      fasCircleNodes,
      fasCity,
      fasClinicMedical,
      fasClipboard,
      fasClipboardCheck,
      fasClipboardList,
      fasClipboardUser,
      fasClock,
      fasClone,
      fasCloudSun,
      fasCog,
      fasCoins,
      fasCommentDots,
      fasComments,
      fasCompressAlt,
      fasCubes,
      fasDatabase,
      fasDesktop,
      fasDoorClosed,
      fasDownload,
      fasDumbbell,
      fasDungeon,
      fasEarListen,
      fasEdit,
      fasEllipsisH,
      fasEllipsisV,
      fasEnvelope,
      fasExchange,
      fasExchangeAlt,
      fasExclamationTriangle,
      fasExpandAlt,
      fasEye,
      fasEyeSlash,
      fasFile,
      fasFileAlt,
      fasFileDownload,
      fasFileInvoice,
      fasFileInvoiceDollar,
      fasFileLines,
      fasFileSignature,
      fasFilter,
      fasFlag,
      fasFloppyDisk,
      fasFolderOpen,
      fasGavel,
      fasGear,
      fasGlobe,
      fasGraduationCap,
      fasGripLinesVertical,
      fasGripLines,
      fasHammer,
      fasHandPaper,
      fasHandshake,
      fasHistory,
      fasHome,
      fasHospital,
      fasHotel,
      fasHouse,
      fasHouseUser,
      fasIdCardAlt,
      fasInbox,
      fasInfoCircle,
      fasLaptopHouse,
      fasLayerGroup,
      fasLevelDownAlt,
      fasLink,
      fasList,
      fasListAlt,
      fasListCheck,
      fasListOl,
      fasListUl,
      fasLock,
      fasMagnifyingGlass,
      fasMap,
      fasMapMarkedAlt,
      fasMapMarkerAlt,
      fasMoneyBillAlt,
      fasMoneyCheck,
      fasMoneyCheckAlt,
      fasMusic,
      fasNetworkWired,
      fasNewspaper,
      fasPaperclip,
      fasPassport,
      fasPauseCircle,
      fasPencil,
      fasPencilAlt,
      fasPeopleArrows,
      fasPeopleArrowsLeftRight,
      fasPersonWalkingDashedLineArrowRight,
      fasPhone,
      fasPiggyBank,
      fasPlus,
      fasPlusCircle,
      fasPray,
      fasProcedures,
      fasPrint,
      fasQuestion,
      fasReceipt,
      fasRedo,
      fasRedoAlt,
      fasRestroom,
      fasRetweet,
      fasRing,
      fasSchool,
      fasScroll,
      fasSearch,
      fasSearchDollar,
      fasShareAlt,
      fasShieldAlt,
      fasShieldHalved,
      fasShoppingBasket,
      fasSignOutAlt,
      fasSitemap,
      fasSmile,
      fasSpinner,
      fasSquare,
      fasSquareXmark,
      fasStar,
      fasStickyNote,
      fasStore,
      fasStreetView,
      fasSync,
      fasTable,
      fasTableCellsLarge,
      fasTableColumns,
      fasTableList,
      fasTag,
      fasTasks,
      fasTh,
      fasThLarge,
      fasThList,
      fasThumbtack,
      fasTimes,
      fasTimesCircle,
      fasTimesSquare,
      fasToilet,
      fasTrash,
      fasTrashAlt,
      fasTriangleExclamation,
      fasTshirt,
      fasTty,
      fasUniversity,
      fasUser,
      fasUserAlt,
      fasUserClock,
      fasUserCog,
      fasUserGear,
      fasUserInjured,
      fasUserLock,
      fasUserMinus,
      fasUserPlus,
      fasUsers,
      fasUsersBetweenLines,
      fasUsersGear,
      fasUserSecret,
      fasUserShield,
      fasUserSlash,
      fasUserTag,
      fasUserTie,
      fasWarehouse,
      fasWheelchair,
      fasXmark,
      faUserFriends,

    );
  }
}
